name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 3 hours
    - cron: '0 */6 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          COMMIT_BY_ME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_COMMIT: "True"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SYMBOL_VERSION: 2
